---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archive-catalog-database
  namespace: {{.Release.Namespace}}
  labels:
    app: archive-catalog-database
spec:
  selector:
    matchLabels:
      app: archive-catalog-database
  template:
    metadata:
      labels:
        app: archive-catalog-database
    spec:
      volumes:
        - name: archive-rest-02-backend-database-data
          emptyDir:
        - name: archive-rest-02-backend-database-var-lib-mysql
          emptyDir:
        - name: archive-rest-02-backend-database-configmap
          configMap:
            name: archive-rest-02-backend-database-configmap
        - name: archive-entrypoint
          configMap:
            name: archive-entrypoint
        - name: archive-database-shared
          configMap:
            name: archive-database-shared
      hostname: archive-catalog-database
      subdomain: tg
      containers:
        - name: archive-catalog-database
          image: {{.Values.containers.mariadb}}
          volumeMounts:
            - mountPath: /data
              name: archive-rest-02-backend-database-data
            - mountPath: /config
              name: archive-rest-02-backend-database-configmap
            - mountPath: /entrypoint-common.sh
              name: archive-entrypoint
              subPath: entrypoint-common.sh
            - mountPath: /entrypoint.sh
              name: archive-entrypoint
              subPath: entrypoint-database.sh
            - mountPath: /etc/my.cnf.d/enforce_tls.cnf
              name: archive-database-shared
              subPath: enforce_tls.cnf
            - mountPath: /var/lib/mysql
              name: archive-rest-02-backend-database-var-lib-mysql
          tty: true
          env:
          - name: IPA_DOMAIN
            value: {{.Values.ipa.domain}}
          - name: IPA_PASSWORD
            value: {{.Values.ipa.password}}
          readinessProbe:
            exec:
              command:
              - "/usr/bin/bash"
              - "-c"
              - "mariadb <<< 'select 1'"
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 12
          livenessProbe:
            exec:
              command:
              - "/usr/bin/bash"
              - "-c"
              - "ping -c1 -w1 ipa.{{.Values.ipa.domain}} && mariadb <<< 'select 1'"
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 12
          securityContext:
            privileged: {{.Values.security.privileged}}
