apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipa
  namespace: {{.Release.Namespace}}
  labels:
    app: ipa
spec:
  selector:
    matchLabels:
      app: ipa
  template:
    metadata:
      labels:
        app: ipa
    spec:
      volumes:
      - name: ipa-configmap
        configMap:
          name: ipa-configmap
      - name: ipa-entrypoint
        configMap:
          name: ipa-entrypoint
      - name: ipa-data
        emptyDir:
      dnsConfig:
        nameservers:
          - 127.0.0.1
      hostname: ipa
      subdomain: tg
      initContainers:
        - name: ipa-init
          image: {{.Values.containers.ipa}}
          tty: true
          env:
          - name: IPA_DOMAIN
            value: {{.Values.ipa.domain}}
          - name: IPA_PASSWORD
            value: {{.Values.ipa.password}}
          volumeMounts:
          - mountPath: /data
            name: ipa-data
          - mountPath: /config
            name: ipa-configmap
          - mountPath: /entrypoint.sh
            name: ipa-entrypoint
            subPath: entrypoint-init.sh
          - mountPath: /entrypoint-common.sh
            name: ipa-entrypoint
            subPath: entrypoint-common.sh
          securityContext:
            privileged: {{.Values.security.privileged}}
      containers:
        - name: ipa
          image: {{.Values.containers.ipa}}
          tty: true
          ports:
          - containerPort: 53
            protocol: TCP
          - containerPort: 53
            protocol: UDP
          - containerPort: 80
            protocol: TCP
          - containerPort: 88
            protocol: TCP
          - containerPort: 88
            protocol: UDP
          - containerPort: 123
            protocol: UDP
          - containerPort: 389
            protocol: TCP
          - containerPort: 443
            protocol: TCP
          - containerPort: 464
            protocol: TCP
          - containerPort: 464
            protocol: UDP
          - containerPort: 636
            protocol: TCP
          env:
          - name: IPA_DOMAIN
            value: {{.Values.ipa.domain}}
          - name: IPA_PASSWORD
            value: {{.Values.ipa.password}}
          volumeMounts:
          - mountPath: /data
            name: ipa-data
          - mountPath: /config
            name: ipa-configmap
          - mountPath: /entrypoint.sh
            name: ipa-entrypoint
            subPath: entrypoint.sh
          - mountPath: /entrypoint-common.sh
            name: ipa-entrypoint
            subPath: entrypoint-common.sh
          readinessProbe:
            exec:
              command:
              - "/usr/bin/bash"
              - "-c"
              - "[ -f /ipa.ready ] && /usr/sbin/ipactl status"
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 12
          livenessProbe:
            exec:
              command:
              - "/usr/bin/bash"
              - "-c"
              - "[ -f /ipa.ready ] && /usr/sbin/ipactl status"
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 12
          securityContext:
            privileged: {{.Values.security.privileged}}
